import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils"
import SideNavBar from "../components/SideNavbar"

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen w-full bg-white text-black flex", inter.className, {
        "debug-screens": process.env.NODE_ENV === "development",
      })}>
        {/**Sidebar**/}
        {/**Main Content**/}
        {/* <p className="border">SideBar</p> */}
        <SideNavBar />
        <div className="p-8 w-full">{children}</div>
        </body>
    </html>
  );
}
