import type { Metadata } from "next";
import SideNavBar from "@/components/SideNavbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex">
      
        <SideNavBar />
        <div className="p-8 w-full">{children}</div>
        
    </main>
  );
}
